export const FETCH_GAME_START = 'FETCH_QUIZES_START'
export const FETCH_GAME_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_GAME_ERROR = 'FETCH_QUIZES_ERROR'
export const FETCH_GMPD_SUCCESS = 'FETCH_GMPD_SUCCESS'

export const RECIEVED_MAPPOINTS = 'RECIEVED_MAPPOINTS'

export const FETCH_CHAT_START = 'FETCH_CHAT_START'
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS'
export const RECV_CHRLIST = 'RECV_CHRLIST'
export const RECV_CHRDES = 'RECV_CHRDES'
export const FETCH_CHAT_ERROR = 'FETCH_CHAT_ERROR'
export const CLEAR_CHAT = 'CLEAR_CHAT'

export const RECV_COMMANDS = 'RECV_COMMANDS'
export const RECV_SETTINGS = 'RECV_SETTINGS'

export const ADD_LOG = 'ADD_LOG'
